CREATE TABLE functions (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    format INTEGER,
    func_result VARCHAR(2048),
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);