CREATE TABLE points (
    id BIGSERIAL PRIMARY KEY,
    function_id BIGINT NOT NULL,
    point_index INTEGER NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (function_id) REFERENCES functions(id) ON DELETE CASCADE
);